description: >
  Create a Docker image

parameters:
  maven-settings:
    description: Location of Maven settings file
    type: string
    default: .circleci/settings.xml
  maven-flags:
    description: Additional flags to pass to Maven
    type: string
    default: -B -q -Ddependency-check.skip=true -DskipTests=true -Dcheckstyle.skip

steps:
  - cache-dependencies
  - setup_remote_docker
  - run:
      name: Create application JAR
      command: |
        mvn -s << parameters.maven-settings >> << parameters.maven-flags >> package
