description: >
  Create a Docker image

parameters:
  maven-settings:
    description: Location of Maven settings file
    type: string
    default: .circleci/settings.xml
  maven-flags:
    description: Additional flags to pass to Maven
    type: string
    default: -B -q -Ddependency-check.skip=true -DskipTests=true -Dcheckstyle.skip
  repository:
    description: ECR repository containing the image
    type: string
    default: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/achievementnetwork/${CIRCLE_PROJECT_REPONAME}
  tag:
    description: Tag of the Docker image
    type: string
    default: ${CIRCLE_SHA1:0:7}

steps:
  - cache-dependencies
  - setup_remote_docker
  - run:
      name: Create Docker image
      command: |
        mvn -s << parameters.maven-settings >> << parameters.maven-flags >> -Ddockerfile.repository=<<parameters.repository>> -Ddockerfile.tag=<<parameters.tag>> package dockerfile:build dockerfile:tag
