description: >
  Default executor for Java/Spring Boot projects

docker:
  - image: cimg/openjdk:<<parameters.version>>.0

parameters:
  version:
    description: >
      The version of Java to use
    type: string
    default: '11'
