description: >
  Default executor for Java/Spring Boot projects

docker:
  - image: circleci/openjdk:<<parameters.version>>-jdk

parameters:
  version:
    description: >
      The version of Java to use
    type: string
    default: '11'
